"""add_haversine

Revision ID: 330c9ac7bfac
Revises: 176db6ff5a87
Create Date: 2023-12-04 18:42:56.707507

"""
import sqlalchemy as sa  # noqa: F401
import sqlmodel  # noqa: F401
from alembic import op

# revision identifiers, used by Alembic.
revision = "330c9ac7bfac"
down_revision = "176db6ff5a87"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
    CREATE OR REPLACE FUNCTION haversine(lat1 FLOAT, lon1 FLOAT, lat2 FLOAT, lon2 FLOAT)
    RETURNS FLOAT AS $$
    DECLARE
        R INT := 6371;  -- Earth radius in kilometers
        phi1 FLOAT;
        phi2 FLOAT;
        d_phi FLOAT;
        d_lambda FLOAT;
        a FLOAT;
        c FLOAT;
        d FLOAT;
    BEGIN
        phi1 := RADIANS(lat1);
        phi2 := RADIANS(lat2);
        d_phi := RADIANS(lat2 - lat1);
        d_lambda := RADIANS(lon2 - lon1);

        a := SIN(d_phi / 2) * SIN(d_phi / 2) +
            COS(phi1) * COS(phi2) *
            SIN(d_lambda / 2) * SIN(d_lambda / 2);
        c := 2 * ATAN2(SQRT(a), SQRT(1-a));
        d := R * c;  -- Distance in kilometers

        RETURN d;
    END;
    $$ LANGUAGE plpgsql;
    """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP FUNCTION haversine")
    # ### end Alembic commands ###
