"""init

Revision ID: 3cfa163547fa
Revises: No down revision
Create Date: 2023-12-22 15:18:28.844932

"""
import sqlalchemy as sa  # noqa: F401
import sqlmodel  # noqa: F401
from alembic import op
from app.types import get_unified_types

# revision identifiers, used by Alembic.
revision = "3cfa163547fa"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "building_element_upload",
        sa.Column(
            "created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "collector",
        sa.Column(
            "created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("zip_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "contractor",
        sa.Column(
            "created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("zip_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    unified_type_table = op.create_table(
        "unified_type",
        sa.Column("discriminator", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("type_id", sa.Integer(), nullable=False),
        sa.Column("type_label", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_unified_type_discriminator"), "unified_type", ["discriminator"], unique=False)
    op.create_index(op.f("ix_unified_type_type_label"), "unified_type", ["type_label"], unique=False)
    op.bulk_insert(
        unified_type_table,
        get_unified_types(),
    )
    op.create_table(
        "building_element",
        sa.Column(
            "created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("reference", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("total", sa.Float(), nullable=True),
        sa.Column("total_mass_kg", sa.Float(), nullable=True),
        sa.Column("total_volume_m3", sa.Float(), nullable=True),
        sa.Column("has_energy_recovery", sa.Boolean(), nullable=True),
        sa.Column("has_elimination", sa.Boolean(), nullable=True),
        sa.Column("building_element_upload_id", sa.Integer(), nullable=False),
        sa.Column("worksheet_type_id", sa.Integer(), nullable=False),
        sa.Column("unit_type_id", sa.Integer(), nullable=False),
        sa.Column("material_type_id", sa.Integer(), nullable=True),
        sa.Column("health_status_type_id", sa.Integer(), nullable=True),
        sa.Column("reuse_potential_type_id", sa.Integer(), nullable=True),
        sa.Column("waste_code_type_id", sa.Integer(), nullable=True),
        sa.Column("recycling_potential_type_id", sa.Integer(), nullable=True),
        sa.Column("circular_service_needed_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["building_element_upload_id"],
            ["building_element_upload.id"],
        ),
        sa.ForeignKeyConstraint(
            ["circular_service_needed_id"],
            ["unified_type.id"],
        ),
        sa.ForeignKeyConstraint(
            ["health_status_type_id"],
            ["unified_type.id"],
        ),
        sa.ForeignKeyConstraint(
            ["material_type_id"],
            ["unified_type.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recycling_potential_type_id"],
            ["unified_type.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reuse_potential_type_id"],
            ["unified_type.id"],
        ),
        sa.ForeignKeyConstraint(
            ["unit_type_id"],
            ["unified_type.id"],
        ),
        sa.ForeignKeyConstraint(
            ["waste_code_type_id"],
            ["unified_type.id"],
        ),
        sa.ForeignKeyConstraint(
            ["worksheet_type_id"],
            ["unified_type.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "collector_to_authorized_vehicle_type",
        sa.Column("collector_id", sa.Integer(), nullable=False),
        sa.Column("unified_type_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collector_id"],
            ["collector.id"],
        ),
        sa.ForeignKeyConstraint(
            ["unified_type_id"],
            ["unified_type.id"],
        ),
        sa.PrimaryKeyConstraint("collector_id", "unified_type_id"),
    )
    op.create_table(
        "collector_to_circular_strategy_type",
        sa.Column("collector_id", sa.Integer(), nullable=False),
        sa.Column("unified_type_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collector_id"],
            ["collector.id"],
        ),
        sa.ForeignKeyConstraint(
            ["unified_type_id"],
            ["unified_type.id"],
        ),
        sa.PrimaryKeyConstraint("collector_id", "unified_type_id"),
    )
    op.create_table(
        "collector_to_material_type",
        sa.Column("collector_id", sa.Integer(), nullable=False),
        sa.Column("unified_type_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collector_id"],
            ["collector.id"],
        ),
        sa.ForeignKeyConstraint(
            ["unified_type_id"],
            ["unified_type.id"],
        ),
        sa.PrimaryKeyConstraint("collector_id", "unified_type_id"),
    )
    op.create_table(
        "collector_to_waste_code_type",
        sa.Column("collector_id", sa.Integer(), nullable=False),
        sa.Column("unified_type_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collector_id"],
            ["collector.id"],
        ),
        sa.ForeignKeyConstraint(
            ["unified_type_id"],
            ["unified_type.id"],
        ),
        sa.PrimaryKeyConstraint("collector_id", "unified_type_id"),
    )
    op.create_table(
        "contractor_to_circular_service_type",
        sa.Column("contractor_id", sa.Integer(), nullable=False),
        sa.Column("unified_type_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["contractor_id"],
            ["contractor.id"],
        ),
        sa.ForeignKeyConstraint(
            ["unified_type_id"],
            ["unified_type.id"],
        ),
        sa.PrimaryKeyConstraint("contractor_id", "unified_type_id"),
    )
    op.create_table(
        "contractor_to_material_type",
        sa.Column("contractor_id", sa.Integer(), nullable=False),
        sa.Column("unified_type_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["contractor_id"],
            ["contractor.id"],
        ),
        sa.ForeignKeyConstraint(
            ["unified_type_id"],
            ["unified_type.id"],
        ),
        sa.PrimaryKeyConstraint("contractor_id", "unified_type_id"),
    )
    op.create_table(
        "contractor_to_waste_code_type",
        sa.Column("contractor_id", sa.Integer(), nullable=False),
        sa.Column("unified_type_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["contractor_id"],
            ["contractor.id"],
        ),
        sa.ForeignKeyConstraint(
            ["unified_type_id"],
            ["unified_type.id"],
        ),
        sa.PrimaryKeyConstraint("contractor_id", "unified_type_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("contractor_to_waste_code_type")
    op.drop_table("contractor_to_material_type")
    op.drop_table("contractor_to_circular_service_type")
    op.drop_table("collector_to_waste_code_type")
    op.drop_table("collector_to_material_type")
    op.drop_table("collector_to_circular_strategy_type")
    op.drop_table("collector_to_authorized_vehicle_type")
    op.drop_table("building_element")
    op.drop_index(op.f("ix_unified_type_type_label"), table_name="unified_type")
    op.drop_index(op.f("ix_unified_type_discriminator"), table_name="unified_type")
    op.drop_table("unified_type")
    op.drop_table("contractor")
    op.drop_table("collector")
    op.drop_table("building_element_upload")
    # ### end Alembic commands ###
